### ISSUE TITLE
リクエストに既に登録済みの音 MAD を紐付けるための Mutation

### ISSUE THREAD

**Issue by SnO2WMaN** [otomadb/graphql-api#1130]
- [ ] otomadb/graphql-api#1125
- [ ] otomadb/graphql-api#1124
- [x] otomadb/api#1111
- [ ] otomadb/graphql-api#1123
